env_name: huarubattle
map_name: battle5v5
mode: parallel
# mode: host  #设置host模式启动容器时挂载回放文件，具体挂载位置见harl/envs/battle5v5/env/xsim_manager.py 44行
episode_limit: 80
num_agents: 5
time_step: 0

ADDRESS: {
    "ip": "127.0.0.1",
    "port": 40001
}

